INSERT INTO courses (course_code, course_name, faculty_code) VALUES
('ACCT3603', 'Hệ thống thông tin kế toán', 'HTTT'),
('ACCT5123', 'Hoạch định nguồn lực doanh nghiệp', 'HTTT'),
('ADENG1', 'Tiếng Anh tăng cường 1', 'HTTT'),
('ADENG2', 'Tiếng Anh tăng cường 2', 'HTTT'),
('ADENG3', 'Tiếng Anh tăng cường 3', 'HTTT'),
('ADENG4', 'Tiếng Anh tăng cường 4', 'HTTT'),
('AI001', 'Giới thiệu ngành Trí tuệ nhân tạo', 'KHMT'),
('AI002', 'Tư duy Trí tuệ nhân tạo', 'KHMT'),
('AI301', 'Khởi nghiệp và sáng tạo', 'KHMT'),
('AI302', 'Kỹ thuật viết báo cáo và trình bày', 'KHMT'),
('AI503', 'Đồ án tốt nghiệp', 'KHMT'),
('AI504', 'Đồ án tốt nghiệp tại doanh nghiệp', 'KHMT'),
('AI505', 'Khoá luận tốt nghiệp', 'KHMT'),
('BCH058', 'Kỹ năng truyền thông giao tiếp', 'P.DTDH'),
('BOQC1', 'Nhập môn máy tính lượng tử', 'BMTL'),
('BUS1125', 'Khởi nghiệp kinh doanh', 'P.DTDH'),
('CARC1', 'Kiến trúc máy tính', 'KTMT'),
('CE005', 'Giới thiệu ngành Kỹ Thuật Máy tính', 'KTMT'),
('CE006', 'Giới thiệu ngành Thiết kế vi mạch', 'KTMT'),
('CE101', 'Lý thuyết mạch điện', 'KTMT'),
('CE102', 'Hệ thống số', 'KTMT'),
('CE103', 'Vi xử lý-vi điều khiển', 'KTMT'),
('CE104', 'Các thiết bị và mạch điện tử', 'KTMT'),
('CE105', 'Xử lý tín hiệu số', 'KTMT'),
('CE106', 'Thiết kế vi mạch với HDL', 'KTMT'),
('CE107', 'Hệ thống nhúng', 'KTMT'),
('CE108', 'Hệ điều hành nâng cao', 'KTMT'),
('CE109', 'Lập trình nhúng căn bản', 'KTMT'),
('CE110', 'Lập trình hệ thống với Java', 'KTMT'),
('CE111', 'Kiến trúc máy tính nâng cao', 'KTMT'),
('CE112', 'Đồ án môn học thiết kế mạch', 'KTMT'),
('CE113', 'Điều khiển tự động', 'KTMT'),
('CE114', 'Lập trình trên thiết bị di động', 'KTMT'),
('CE115', 'Thiết kế mạng', 'KTMT'),
('CE116', 'Đồ án môn học ngành KTMT', 'KTMT'),
('CE117', 'Thực hành điện- điện tử', 'KTMT'),
('CE118', 'Thiết kế luận lý số', 'KTMT'),
('CE119', 'Thực hành Kiến trúc máy tính', 'KTMT'),
('CE121', 'Lý thuyết mạch điện', 'KTMT'),
('CE122', 'Phân tích mạch kỹ thuật', 'KTMT'),
('CE124', 'Các thiết bị và mạch điện tử', 'KTMT'),
('CE125', 'Kỹ thuật phân tích mạch', 'KTMT'),
('CE126', 'Vật lý bán dẫn và ứng dụng', 'KTMT'),
('CE201', 'Đồ án 1', 'KTMT'),
('CE202', 'An toàn mạng máy tính', 'KTMT'),
('CE203', 'Điều khiển tự động nâng cao', 'KTMT'),
('CE204', 'Thiết kế và lập trình Web', 'KTMT'),
('CE205', 'Xử lý tín hiệu số', 'KTMT'),
('CE206', 'Đồ án 2', 'KTMT'),
('CE207', 'Đồ án Thiết kế vi mạch 1', 'KTMT'),
('CE208', 'Đồ án Thiết kế vi mạch 2', 'KTMT'),
('CE211', 'Lập trình nhúng căn bản', 'KTMT'),
('CE212', 'Điều khiển tự động', 'KTMT'),
('CE213', 'Thiết kế hệ thống số với HDL', 'KTMT'),
('CE219', 'Tương tác người - máy', 'KTMT'),
('CE221', 'Thiết kế vi mạch với HDL', 'KTMT'),
('CE222', 'Thiết kế vi mạch số', 'KTMT'),
('CE224', 'Thiết kế hệ thống nhúng', 'KTMT'),
('CE226', 'Thiết kế VLSI', 'KTMT'),
('CE232', 'Thiết kế hệ thống nhúng không dây', 'KTMT'),
('CE233', 'Kỹ thuật Robot', 'KTMT'),
('CE301', 'Hệ thống chứng thực số', 'KTMT'),
('CE302', 'Thiết kế vi mạch', 'KTMT'),
('CE303', 'Robot công nghiệp', 'KTMT'),
('CE3031', 'Công nghệ cảm biến', 'KTMT'),
('CE304', 'Robot công nghiệp', 'KTMT'),
('CE306', 'Thị giác máy tính', 'KTMT'),
('CE312', 'Hệ thống thời gian thực', 'KTMT'),
('CE313', 'Xử lý song song và hệ thống phân tán', 'KTMT'),
('CE314', 'Trình biên dịch', 'KTMT'),
('CE315', 'Lập trình hệ thống với Java', 'KTMT'),
('CE316', 'Logic mờ và ứng dụng', 'KTMT'),
('CE317', 'Điều khiển tự động nâng cao', 'KTMT'),
('CE318', 'Trình biên dịch', 'KTMT'),
('CE319', 'Logic mờ và ứng dụng', 'KTMT'),
('CE320', 'Logic mờ cho ứng dụng hệ thống nhúng', 'KTMT'),
('CE321', 'Kỹ thuật chế tạo vi mạch', 'KTMT'),
('CE322', 'Thiết kế vi mạch hỗn hợp', 'KTMT'),
('CE323', 'Kĩ thuật thiết kế mạch in', 'KTMT'),
('CE324', 'Thiết kế vi mạch tương tự', 'KTMT'),
('CE325', 'Thiết kế dựa trên vi xử lý', 'KTMT'),
('CE326', 'Tự động hóa thiết kế vi mạch', 'KTMT'),
('CE327', 'Tối ưu hóa dựa trên FPGA', 'KTMT'),
('CE331', 'Kỹ thuật chế tạo vi mạch', 'KTMT'),
('CE332', 'Thiết kế vi mạch hỗn hợp', 'KTMT'),
('CE333', 'Tiếng Anh chuyên ngành Kỹ thuật Máy tính', 'KTMT'),
('CE334', 'Thiết kế vi mạch tương tự', 'KTMT'),
('CE335', 'Thiết kế dựa trên vi xử lý', 'KTMT'),
('CE336', 'Tự động hóa thiết kế vi mạch', 'KTMT'),
('CE337', 'Tối ưu hóa dựa trên FPGA', 'KTMT'),
('CE338', 'Hệ thống thời gian thực', 'KTMT'),
('CE339', 'Công nghệ IoT và Ứng dụng', 'KTMT'),
('CE340', 'Trí tuệ nhân tạo cho hệ thống nhúng', 'KTMT'),
('CE341', 'Lập trình nhúng trên các thiết bị di động', 'KTMT'),
('CE342', 'Hệ thống thông minh', 'KTMT'),
('CE343', 'Trí tuệ nhân tạo cho xe tự hành', 'KTMT'),
('CE344', 'Trí tuệ nhân tạo cho IoT', 'KTMT'),
('CE345', 'Kiến trúc IoT: Giao thức mạng và bảo mật', 'KTMT'),
('CE346', 'Thiết kế Antenna tích hợp cho thiết bị IoT', 'KTMT'),
('CE347', 'Điều khiển thông minh cho robot', 'KTMT'),
('CE348', 'Công nghệ cảm biến trong IoT', 'KTMT'),
('CE349', 'Hệ thống nhúng trên SoC', 'KTMT'),
('CE350', 'Xử lý ảnh hướng ASIC', 'KTMT'),
('CE351', 'Thiết kế bộ tăng tốc phần cứng', 'KTMT'),
('CE352', 'Xử lý tín hiệu số trên FPGA', 'KTMT'),
('CE353', 'Thiết kế vật lý vi mạch', 'KTMT'),
('CE401', 'Kỹ thuật hệ thống máy tính', 'KTMT'),
('CE402', 'Các hệ điều hành nhúng', 'KTMT'),
('CE403', 'Thiết kế số', 'KTMT'),
('CE404', 'Kỹ thuật chế tạo vi mạch', 'KTMT'),
('CE405', 'Tương tác người máy', 'KTMT'),
('CE406', 'Tương tác người – Máy', 'KTMT'),
('CE407', 'Đồ án chuyên ngành Hệ thống nhúng và Robot', 'KTMT'),
('CE408', 'Đồ án chuyên ngành Thiết kế vi mạch và phần cứng', 'KTMT'),
('CE409', 'Kỹ thuật thiết kế kiểm tra', 'KTMT'),
('CE410', 'Kỹ thuật hệ thống máy tính', 'KTMT'),
('CE411', 'Chuyên đề hệ thống nhúng và robot', 'KTMT'),
('CE412', 'Đồ án chuyên ngành Hệ thống nhúng và IoT', 'KTMT'),
('CE413', 'Đồ án chuyên ngành Robotics và AI', 'KTMT'),
('CE421', 'Chuyên đề thiết kế vi mạch và phần cứng', 'KTMT'),
('CE430', 'Lập trình hệ thống', 'KTMT'),
('CE432', 'Thiết kế vi mạch hướng ASIC', 'KTMT'),
('CE433', 'Thiết kế hệ thống SoC', 'KTMT'),
('CE434', 'Chuyên đề thiết kế hệ vi mạch 1', 'KTMT'),
('CE435', 'Chuyên đề thiết kế hệ vi mạch 2', 'KTMT'),
('CE436', 'Xử lý tín hiệu số và ứng dụng', 'KTMT'),
('CE437', 'Chuyên đề thiết kế hệ thống nhúng 1', 'KTMT'),
('CE438', 'Chuyên đề thiết kế hệ thống nhúng 2', 'KTMT'),
('CE439', 'Lập trình song song và hệ phân tán', 'KTMT'),
('CE440', 'Hệ thống định vị với ứng dụng AI', 'KTMT'),
('CE441', 'Chuyên đề thiết kế Robotics và AI 1', 'KTMT'),
('CE442', 'Chuyên đề thiết kế Robotics và AI 2', 'KTMT'),
('CE501', 'Thực tập doanh nghiệp', 'KTMT'),
('CE502', 'Thực tập doanh nghiệp', 'KTMT'),
('CE505', 'Khóa luận tốt nghiệp', 'KTMT'),
('CE506', 'Luận văn chuyên sâu đặc thù', 'KTMT'),
('CE507', 'Đồ án tốt nghiệp tại doanh nghiệp', 'KTMT'),
('CE508', 'Đồ án tốt nghiệp', 'KTMT'),
('CE510', 'Chuyên đề tốt nghiệp định hướng Hệ thống nhúng và IoT', 'KTMT'),
('CE511', 'Chuyên đề tốt nghiệp định hướng Robotic và AI', 'KTMT'),
('CE512', 'Chuyên đề tốt nghiệp định hướng thiết kế vi mạch', 'KTMT'),
('CM101', 'Quản lý giao tiếp', 'HTTT'),
('CNBU001', 'Mạng máy tính', 'MMT&TT'),
('CNBU002', 'Bảo mật', 'MMT&TT'),
('CNBU003', 'Dự án nghiên cứu', 'MMT&TT'),
('CNBU004', 'Thiết kế và phát triển website', 'MMT&TT'),
('CNBU005', 'Internet of Things', 'MMT&TT'),
('CNBU006', 'An toàn mạng máy tính', 'MMT&TT'),
('CNBU007', 'Pháp chứng kỹ thuật số', 'MMT&TT'),
('CNBU008', 'Quản lý an toàn thông tin', 'MMT&TT'),
('CNBU009', 'Thực tập', 'MMT&TT'),
('CNBU101', 'Toán cho Tin học', 'MMT&TT'),
('CNBU102', 'Công nghệ mạng máy tính', 'MMT&TT'),
('CNBU103', 'Lập trình cho kỹ sư mạng máy tính', 'MMT&TT'),
('CNBU104', 'Hệ thống Servers', 'MMT&TT'),
('CNBU105', 'Hệ thống mạng doanh nghiệp', 'MMT&TT'),
('CNBU106', 'Hoạt động an ninh mạng', 'MMT&TT'),
('CNBU107', 'Dự án chuyên ngành', 'MMT&TT'),
('CNBU108', 'Hệ điều hành', 'MMT&TT'),
('CNBU201', 'Công nghệ mạng không dây', 'MMT&TT'),
('CNBU202', 'Hệ thống tường lửa nâng cao', 'MMT&TT'),
('CNBU203', 'An toàn mạng máy tính', 'MMT&TT'),
('CNBU204', 'Ethical Hacking', 'MMT&TT'),
('CNBU205', 'Dự án cá nhân', 'MMT&TT'),
('CNET1', 'Mạng máy tính', 'MMT&TT'),
('CS003', 'Máy học nâng cao', 'KHMT'),
('CS004', 'Máy học trong xử lý ngôn ngữ tự nhiên', 'KHMT'),
('CS005', 'Giới thiệu ngành Khoa học Máy tính', 'KHMT'),
('CS013', 'Máy học nâng cao', 'KHMT'),
('CS014', 'Máy học trong xử lý ngôn ngữ tự nhiên', 'KHMT'),
('CS019', 'Chuyên đề ứng dụng Trí tuệ nhân tạo', 'KHMT'),
('CS101', 'Nguyên lý và phương pháp lập trình', 'KHMT'),
('CS102', 'Phân tích & thiết kế thuật toán', 'KHMT'),
('CS103', 'Cơ sở lập trình', 'KHMT'),
('CS104', 'Nhập môn công nghệ phần mềm', 'KHMT'),
('CS105', 'Đồ họa máy tính', 'KHMT'),
('CS106', 'Trí tuệ nhân tạo', 'KHMT'),
('CS107', 'Các hệ cơ sở tri thức', 'KHMT'),
('CS108', 'Lý thuyết thông tin', 'KHMT'),
('CS109', 'Máy học', 'KHMT'),
('CS110', 'Nhập môn công nghệ tri thức & máy học', 'KHMT'),
('CS111', 'Nguyên lý và phương pháp lập trình', 'KHMT'),
('CS1113', 'Khoa học máy tính I', 'HTTT'),
('CS112', 'Phân tích và thiết kế thuật toán', 'KHMT'),
('CS113', 'Đồ họa máy tính và Xử lý ảnh', 'KHMT'),
('CS114', 'Máy học', 'KHMT'),
('CS115', 'Toán cho Khoa học máy tính', 'KHMT'),
('CS116', 'Lập trình Python cho Máy học', 'KHMT'),
('CS117', 'Tư duy tính toán', 'KHMT'),
('CS210', 'Xử lý ngôn ngữ tự nhiên nâng cao', 'KHMT'),
('CS211', 'Trí tuệ nhân tạo nâng cao', 'KHMT'),
('CS212', 'Xử lý ngôn ngữ tự nhiên', 'KHMT'),
('CS213', 'Ngôn ngữ học máy tính', 'KHMT'),
('CS2133', 'Khoa học máy tính II', 'HTTT'),
('CS2134', 'Khoa học máy tính', 'HTTT'),
('CS214', 'Biểu diễn tri thức và suy luận', 'KHMT'),
('CS217', 'Các hệ cơ sở tri thức', 'KHMT'),
('CS221', 'Xử lý ngôn ngữ tự nhiên', 'KHMT'),
('CS222', 'Xử lý ngôn ngữ tự nhiên nâng cao', 'KHMT'),
('CS223', 'Máy học nâng cao', 'KHMT'),
('CS224', 'Máy học xử lý ngôn ngữ tự nhiên', 'KHMT'),
('CS225', 'Lập trình symbolic trong trí tuệ nhân tạo', 'KHMT'),
('CS226', 'Ngôn ngữ học máy tính', 'KHMT'),
('CS227', 'Khai thác dữ liệu và ứng dụng', 'KHMT'),
('CS228', 'Máy học và ứng dụng', 'KHMT'),
('CS229', 'Ngữ nghĩa học tính toán', 'KHMT'),
('CS231', 'Nhập môn Thị giác máy tính', 'KHMT'),
('CS232', 'Tính toán đa phương tiện', 'KHMT'),
('CS233', 'Nhận dạng Thị giác', 'KHMT'),
('CS2433', 'Lập trình C/C++', 'HTTT'),
('CS301', 'Chuyên đề nghiên cứu khoa học', 'KHMT'),
('CS302', 'Seminar', 'KHMT'),
('CS311', 'Kỹ thuật lập trình trí tuệ nhân tạo', 'KHMT'),
('CS312', 'Hệ thống đa tác tử', 'KHMT'),
('CS313', 'Khai thác dữ liệu và ứng dụng', 'KHMT'),
('CS314', 'Lập trình symbolic trong trí tuệ nhân tạo', 'KHMT'),
('CS315', 'Máy học nâng cao', 'KHMT'),
('CS316', 'Các hệ giải bài toán thông minh', 'KHMT'),
('CS317', 'Phát triển và vận hành hệ thống máy học', 'KHMT'),
('CS321', 'Ngôn ngữ học ngữ liệu', 'KHMT'),
('CS322', 'Biểu diễn tri thức và ứng dụng', 'KHMT'),
('CS323', 'Các hệ thống hỏi-đáp', 'KHMT'),
('CS324', 'Máy học trong xử lý ngôn ngữ tự nhiên', 'KHMT'),
('CS325', 'Dịch máy', 'KHMT'),
('CS326', 'Các kĩ thuật trong xử lý ngôn ngữ tự nhiên', 'KHMT'),
('CS331', 'Thị giác máy tính nâng cao', 'KHMT'),
('CS332', 'Máy học trong Thị giác Máy tính', 'KHMT'),
('CS333', 'Đồ họa game', 'KHMT'),
('CS334', 'Lập trình tính toán hình thức', 'KHMT'),
('CS335', 'Tìm Kiếm Ảnh và Video', 'KHMT'),
('CS336', 'Truy vấn thông tin đa phương tiện', 'KHMT'),
('CS3363', 'Tổ chức ngôn ngữ lập trình', 'HTTT'),
('CS337', 'Xử lý âm thanh và tiếng nói', 'KHMT'),
('CS3373', 'Lập trình hướng đối tượng nâng cao cho môi trường windows', 'HTTT'),
('CS338', 'Nhận dạng', 'KHMT'),
('CS339', 'Xử lý văn bản Y khoa', 'KHMT'),
('CS3423', 'Cấu trúc tập tin', 'HTTT'),
('CS3443', 'Hệ thống máy tính', 'HTTT'),
('CS351', 'Chuyên đề NCKH 1', 'KHMT'),
('CS3513', 'Phương pháp số cho máy tính kỹ thuật số', 'HTTT'),
('CS352', 'Chuyên đề NCKH 2', 'KHMT'),
('CS3613', 'Cơ sở tính toán', 'HTTT'),
('CS3653', 'Toán rời rạc cho máy tính', 'HTTT'),
('CS371', 'Seminar chuyên đề 1', 'KHMT'),
('CS372', 'Seminar chuyên đề 2', 'KHMT'),
('CS401', 'Công nghệ Java', 'KHMT'),
('CS402', 'Phân tích thiết kế HTTT quản lý', 'KHMT'),
('CS403', 'Các dịch vụ web', 'KHMT'),
('CS404', 'Công nghệ đa tác tử (Muli-Agent)', 'KHMT'),
('CS405', 'Logic mờ và ứng dụng', 'KHMT'),
('CS406', 'Xử lý ảnh và ứng dụng', 'KHMT'),
('CS407', 'Các kỹ thuật trong xử lý NNTN', 'KHMT'),
('CS408', 'Các hệ giải toán thông minh', 'KHMT'),
('CS409', 'Hệ suy diễn mờ', 'KHMT'),
('CS410', 'Mạng neural và thuật giải di truyền', 'KHMT'),
('CS411', 'Dịch máy', 'KHMT'),
('CS412', 'Web ngữ nghĩa', 'KHMT'),
('CS414', 'Lý thuyết automat và ứng dụng', 'KHMT'),
('CS4143', 'Đồ họa máy tính', 'HTTT'),
('CS415', 'Mã hóa thông tin', 'KHMT'),
('CS4153', 'Phát triển ứng dụng trên di động', 'HTTT'),
('CS417', 'Nhận dạng', 'KHMT'),
('CS418', 'Trực quan máy tính', 'KHMT'),
('CS419', 'Truy xuất thông tin', 'KHMT'),
('CS420', 'Các vấn đề chọn lọc trong Thị giác máy tính', 'KHMT'),
('CS421', 'Khai thác dữ liệu đa phương tiện', 'KHMT'),
('CS4243', 'Thuật toán và tiến trình trong an toàn máy tính', 'HTTT'),
('CS4273', 'Nhập môn Công nghệ phần mềm', 'HTTT'),
('CS4283', 'Mạng máy tính', 'HTTT'),
('CS431', 'Các kĩ thuật học sâu và ứng dụng', 'KHMT'),
('CS4323', 'Hệ điều hành', 'HTTT'),
('CS4343', 'Cấu trúc dữ liệu và giải thuật', 'HTTT'),
('CS4344', 'An ninh mạng', 'HTTT'),
('CS4793', 'Trí tuệ nhân tạo', 'HTTT'),
('CS4883', 'Các vấn đề xã hội trong tính toán', 'HTTT'),
('CS5000', 'Luận văn', 'HTTT'),
('CS501', 'Khóa luận tốt nghiệp', 'KHMT'),
('CS502', 'Các công nghệ web và ứng dụng', 'KHMT'),
('CS503', 'Môn tốt nghiệp KHMT 2', 'KHMT'),
('CS5030', 'Thực tập tốt nghiệp', 'HTTT'),
('CS5031', 'Thực tập doanh nghiệp', 'HTTT'),
('CS504', 'Công nghệ .NET', 'KHMT'),
('CS505', 'Khoá luận tốt nghiệp', 'KHMT'),
('CS506', 'Chuyên đề J2EE', 'KHMT'),
('CS507', 'Hệ điều hành Linux', 'KHMT'),
('CS508', 'Lập trình cơ sở dữ liệu', 'KHMT'),
('CS510', 'Lý thuyết thông tin', 'KHMT'),
('CS511', 'Ngôn ngữ lập trình C#', 'KHMT'),
('CS513', 'Ngôn ngữ lập trình Java', 'KHMT'),
('CS515', 'Phân tích thiết kế hệ thống thông tin', 'KHMT'),
('CS516', 'Phân tích thiết kế hướng đối tượng với UML', 'KHMT'),
('CS517', 'Quản lý dự án', 'KHMT'),
('CS518', 'Xây dựng phần mềm hướng đối tượng', 'KHMT'),
('CS519', 'Phương pháp luận nghiên cứu khoa học', 'KHMT'),
('CS521', 'Toán rời rạc nâng cao', 'KHMT'),
('CS522', 'Đại số máy tính', 'KHMT'),
('CS523', 'Cấu trúc dữ liệu và giải thuật nâng cao', 'KHMT'),
('CS524', 'Một số ứng dụng của xử lý ngôn ngữ tự nhiên', 'KHMT'),
('CS525', 'Thị giác máy tính trong tương tác người – máy', 'KHMT'),
('CS526', 'Phát triển ứng dụng đa phương tiện trên thiết bị di động', 'KHMT'),
('CS527', 'Thực tại ảo', 'KHMT'),
('CS528', 'Trực quan hóa thông tin', 'KHMT'),
('CS529', 'Các vấn đề nghiên cứu và ứng dụng trong khoa học máy tính', 'KHMT'),
('CS530', 'Đồ án chuyên ngành', 'KHMT'),
('CS531', 'Đồ họa trong video game', 'KHMT'),
('CS532', 'Thị giác máy tính trong tương tác người-máy', 'KHMT'),
('CS534', 'Lập trình Javascript và ứng dụng', 'KHMT'),
('CS535', 'Tổng hợp tiếng nói', 'KHMT'),
('CS5423', 'Nguyên lý các hệ cơ sở dữ liệu', 'HTTT'),
('CS5433', 'Các hệ cơ sở dữ liệu phân tán', 'HTTT'),
('CS551', 'Thực tập', 'KHMT'),
('CS553', 'Đồ án tốt nghiệp', 'KHMT'),
('CS554', 'Đồ án tốt nghiệp tại doanh nghiệp', 'KHMT'),
('CSBU001', 'Lập trình', 'KHMT'),
('CSBU002', 'Mạng máy tính', 'KHMT'),
('CSBU003', 'Thực hành nghề nghiệp', 'KHMT'),
('CSBU004', 'Toán cho Tin học', 'KHMT'),
('CSBU005', 'Bảo mật', 'KHMT'),
('CSBU006', 'Quản lý dự án máy tính thành công', 'KHMT'),
('CSBU007', 'Thiết kế và phát triển cơ sở dữ liệu', 'KHMT'),
('CSBU008', 'Kiến trúc máy tính', 'KHMT'),
('CSBU009', 'Dự án nghiên cứu', 'KHMT'),
('CSBU010', 'Công nghệ kinh doanh thông minh', 'KHMT'),
('CSBU011', 'Toán rời rạc', 'KHMT'),
('CSBU012', 'Cấu trúc dữ liệu và giải thuật', 'KHMT'),
('CSBU013', 'Lập trình nâng cao', 'KHMT'),
('CSBU014', 'Máy học', 'KHMT'),
('CSBU015', 'Điện toán đám mây', 'KHMT'),
('CSBU016', 'Thực tập', 'KHMT'),
('CSBU101', 'Lập trình máy tính', 'KHMT'),
('CSBU102', 'Hệ thống máy tính', 'KHMT'),
('CSBU103', 'Phát triển và thiết kế web', 'KHMT'),
('CSBU104', 'Cấu trúc dữ liệu và giải thuật', 'KHMT'),
('CSBU105', 'Mạng máy tính căn bản', 'KHMT'),
('CSBU106', 'Đồ án đổi mới sáng tạo', 'KHMT'),
('CSBU107', 'Lập trình hướng đối tượng', 'KHMT'),
('CSBU108', 'Hệ điều hành', 'KHMT'),
('CSBU109', 'Phát triển ứng dụng web và cơ sở dữ liệu', 'KHMT'),
('CSBU110', 'Toán rời rạc và Lập trình khai báo', 'KHMT'),
('CSBU111', 'An ninh mạng', 'KHMT'),
('CSBU112', 'Thiết kế phần mềm', 'KHMT'),
('CSBU201', 'Thiết kế trải nghiệm người dùng', 'KHMT'),
('CSBU202', 'Phát triển ứng dụng cho thiết bị di động và thiết bị đeo', 'KHMT'),
('CSBU203', 'Điện toán đám mây', 'KHMT'),
('CSBU204', 'Trí tuệ nhân tạo và Máy học', 'KHMT'),
('CSBU205', 'Dự án cá nhân', 'KHMT'),
('CSC01', 'Tin học đại cương', 'KHMT'),
('CSC11', 'Khoa học máy tính I', 'KHMT'),
('CSC12', 'Khoa học máy tính II', 'KHMT'),
('CSC21', 'Tin học đại cương (TE)', 'KHMT'),
('CSKI1', 'Kỹ năng truyền thông làm việc nhóm', 'KHMT'),
('CU001', 'Văn hóa doanh nghiệp Nhật', 'KTTT'),
('DAI015', 'Thực hành văn bản Tiếng Việt', 'P.DTDH'),
('DBSS1', 'Cơ sở dữ liệu', 'TTNN'),
('DS005', 'Giới thiệu ngành Khoa học Dữ liệu', 'KTTT'),
('DS101', 'Thống kê và xác suất chuyên sâu', 'KTTT'),
('DS102', 'Học máy thống kê', 'KTTT'),
('DS103', 'Thu thập và tiền xử lý dữ liệu', 'KTTT'),
('DS104', 'Tính toán song song & phân tán', 'KTTT'),
('DS105', 'Phân tích và trực quan dữ liệu', 'KTTT'),
('DS106', 'Tối ưu hóa và ứng dụng', 'KTTT'),
('DS107', 'Tư duy tính toán cho Khoa học dữ liệu', 'KTTT'),
('DS108', 'Tiền xử lý và xây dựng bộ dữ liệu', 'KTTT'),
('DS111', 'Phân tích dữ liệu', 'KTTT'),
('DS200', 'Phân tích dữ liệu lớn', 'KTTT'),
('DS201', 'Deep Learning trong khoa học dữ liệu', 'KTTT'),
('DS202', 'Đồ án khoa học dữ liệu và ứng dụng 1', 'KTTT'),
('DS203', 'Đồ án khoa học dữ liệu và ứng dụng 2', 'KTTT'),
('DS204', 'Đồ án khoa học dữ liệu và ứng dụng', 'KTTT'),
('DS207', 'Đồ án', 'KTTT'),
('DS300', 'Hệ khuyến nghị', 'KTTT'),
('DS301', 'Các giải thuật khai phá dữ liệu lớn', 'KTTT'),
('DS302', 'Phân tích thống kê đa biến', 'KTTT'),
('DS303', 'Thống kê Bayes', 'KTTT'),
('DS304', 'Thiết kế và phân tích thực nghiệm', 'KTTT'),
('DS305', 'Phân tích dữ liệu chuỗi thời gian và ứng dụng', 'KTTT'),
('DS306', 'Phân tích dữ liệu lớn trong tài chính', 'KTTT'),
('DS307', 'Phân tích dữ liệu truyền thông xã hội', 'KTTT'),
('DS308', 'Mô hình đồ thị xác suất', 'KTTT'),
('DS309', 'Thực tập doanh nghiệp', 'KTTT'),
('DS310', 'Xử lý ngôn ngữ tự nhiên cho Khoa học dữ liệu', 'KTTT'),
('DS311', 'Kỹ năng nghiên cứu và viết bài báo khoa học', 'KTTT'),
('DS312', 'Xử lý ảnh y khoa', 'KTTT'),
('DS313', 'Xử lý thông tin giọng nói', 'KTTT'),
('DS314', 'Rút trích và truy vấn thông tin', 'KTTT'),
('DS315', 'Phân tích Kho dữ liệu', 'KTTT'),
('DS316', 'Xây dựng ứng dụng thông minh', 'KTTT'),
('DS317', 'Khai phá dữ liệu trong doanh nghiệp', 'KTTT'),
('DS318', 'Đạo đức trong Trí tuệ nhân tạo và Khoa học dữ liệu', 'KTTT'),
('DS319', 'Mô hình ngôn ngữ lớn', 'KTTT'),
('DS320', 'Học đa thể thức', 'KTTT'),
('DS321', 'Khoa học dữ liệu cho An toàn thông tin', 'KTTT'),
('DS322', 'Thiết kế hệ thống Học máy', 'KTTT'),
('DS323', 'Viết báo cáo kỹ thuật và thuyết trình', 'KTTT'),
('DS324', 'Khai thác dữ liệu ảnh số', 'KTTT'),
('DS325', 'Thiết kế ứng dụng với dữ liệu chuyên sâu', 'KTTT'),
('DS326', 'Khai phá dữ liệu đa phương tiện và ứng dụng', 'KTTT'),
('DS327', 'Các mô hình nền tảng', 'KTTT'),
('DS400', 'Chuyên đề tốt nghiệp Khoa học dữ liệu', 'KTTT'),
('DS501', 'Đồ án tốt nghiệp', 'KTTT'),
('DS502', 'Đồ án tốt nghiệp tại doanh nghiệp', 'KTTT'),
('DS505', 'Khóa luận tốt nghiệp', 'KTTT'),
('DSAL1', 'Cấu trúc dữ liệu và giải thuật', 'TTNN'),
('DSAL2', 'Cấu trúc dữ liệu & giải thuật nâng cao', 'KHMT'),
('DTH039', 'Đô thị học đại cương', 'P.DTDH'),
('EC001', 'Kinh tế học đại cương', 'HTTT'),
('EC002', 'Quản trị doanh nghiệp', 'HTTT'),
('EC003', 'Tiếp thị căn bản', 'HTTT'),
('EC005', 'Giới thiệu ngành Thương mại Điện tử', 'HTTT'),
('EC101', 'Marketing căn bản', 'HTTT'),
('EC201', 'Phân tích thiết kế quy trình nghiệp vụ doanh nghiệp', 'HTTT'),
('EC202', 'Nhập môn quản trị chuỗi cung ứng', 'HTTT'),
('EC203', 'Quản trị quan hệ khách hàng và nhà cung cấp', 'HTTT'),
('EC204', 'Marketing điện tử', 'HTTT'),
('EC208', 'QuẢN trị dự án TMĐT', 'HTTT'),
('EC212', 'Thực tập doanh nghiệp', 'HTTT'),
('EC213', 'Quản trị quan hệ khách hàng và nhà cung cấp', 'HTTT'),
('EC214', 'Nhập môn Quản trị chuỗi cung ứng', 'HTTT'),
('EC219', 'Pháp luật trong thương mại điện tử', 'HTTT'),
('EC222', 'Thực tập doanh nghiệp', 'HTTT'),
('EC229', 'Pháp luật trong thương mại điện tử', 'HTTT'),
('EC232', 'Nguyên lý kế toán', 'HTTT'),
('EC301', 'Tiếp thị trực tuyến (E-Marketing)', 'HTTT'),
('EC302', 'Thiết kế Hệ thống Thương mại điện tử', 'HTTT'),
('EC304', 'Tối ưu hóa công cụ tìm kiếm trong Thương mại điện tử', 'HTTT'),
('EC311', 'Tiếp thị trực tuyến', 'HTTT'),
('EC312', 'Thiết kế hệ thống thương mại điện tử', 'HTTT'),
('EC331', 'Quản trị chiến lược kinh doanh điện tử', 'HTTT'),
('EC332', 'Quản trị sản xuất', 'HTTT'),
('EC333', 'Quản trị tài chính doanh nghiệp', 'HTTT'),
('EC334', 'Quản trị kênh phân phối', 'HTTT'),
('EC335', 'An toàn và bảo mật thương mại điện tử', 'HTTT'),
('EC336', 'Quản trị nhân lực', 'HTTT'),
('EC337', 'Hệ thống thanh toán trực tuyến', 'HTTT'),
('EC338', 'Quản trị bán hàng', 'HTTT'),
('EC401', 'Khóa luận tốt nghiệp', 'HTTT'),
('EC402', 'Phát triển ứng dụng thương mại di động', 'HTTT'),
('EC403', 'Thương mại xã hội', 'HTTT'),
('EC404', 'Đồ án tốt nghiệp', 'HTTT'),
('EC405', 'Đồ án tốt nghiệp tại doanh nghiệp', 'HTTT'),
('ECE02', 'Mạch số', 'BMTL'),
('ECON3313', 'Kinh tế tiền tệ', 'HTTT'),
('EN001', 'Anh văn 1', 'BMAV'),
('EN001.CO', 'English for Communication 1', 'HTTT'),
('EN001.GE', 'General English', 'HTTT'),
('EN002', 'Anh văn 2', 'BMAV'),
('EN002.CO', 'English for Communication 1', 'HTTT'),
('EN002.GE', 'General English', 'HTTT'),
('EN003', 'Anh văn 3', 'BMAV'),
('EN004', 'Anh văn 1', 'BMAV'),
('EN005', 'Anh văn 2', 'BMAV'),
('EN006', 'Anh văn 3', 'BMAV'),
('ENBT', 'Anh văn Bổ túc', 'BMAV'),
('ENG00', 'Anh văn 0', 'TTNN'),
('ENG01', 'Anh văn 1', 'TTNN'),
('ENG02', 'Anh văn 2', 'TTNN'),
('ENG03', 'Anh văn 3', 'TTNN'),
('ENG04', 'Anh văn 4', 'TTNN'),
('ENG05', 'Anh văn 5', 'TTNN'),
('ENG06', 'Kỹ năng thuyết trình tiếng Anh', 'TTNN'),
('ENG07', 'Kỹ Năng Viết Luận', 'TTNN'),
('ENG11', 'Tiếng anh tăng cường I', 'TTNN'),
('ENG12', 'Tiếng anh tăng cường II', 'TTNN'),
('ENG13', 'Tiếng Anh I', 'TTNN'),
('ENG14', 'Tiếng Anh II', 'TTNN'),
('ENG15', 'Tiếng Anh chuyên ngành CNTT', 'TTNN'),
('ENGA1', 'Anh văn sơ cấp 1', 'TTNN'),
('ENGA2', 'Anh văn sơ cấp 2', 'TTNN'),
('ENGBT', 'Anh văn bổ túc', 'TTNN'),
('ENGL1113', 'Tiếng Anh I', 'HTTT'),
('ENGL1213', 'Tiếng Anh II', 'HTTT'),
('ENLS1', 'Nâng cao kỹ năng nghe, nói tiếng Anh 1', 'TTNN'),
('ENLS2', 'Nâng cao kỹ năng nghe, nói tiếng Anh 2', 'TTNN'),
('ENRW1', 'Nâng cao kỹ năng đọc, viết tiếng Anh 1', 'TTNN'),
('ENRW2', 'Nâng cao kỹ năng đọc, viết tiếng Anh 2', 'TTNN'),
('GDH075', 'Tâm lý học giao tiếp', 'P.DTDH'),
('HCMT1', 'Tư tưởng Hồ Chí Minh', 'P.DTDH'),
('IE005', 'Giới thiệu ngành Công nghệ Thông tin', 'KTTT'),
('IE101', 'Cơ sở hạ tầng công nghệ thông tin', 'KTTT'),
('IE102', 'Các công nghệ nền', 'KTTT'),
('IE103', 'Quản lý thông tin', 'KTTT'),
('IE104', 'Internet và công nghệ Web', 'KTTT'),
('IE105', 'Nhập môn bảo đảm và an ninh thông tin', 'KTTT'),
('IE106', 'Thiết kế giao diện người dùng', 'KTTT'),
('IE107', 'Thiết kế giao diện người dùng', 'KTTT'),
('IE108', 'Phân tích thiết kế phần mềm', 'KTTT'),
('IE201', 'Xử lý dữ liệu thống kê', 'KTTT'),
('IE202', 'Quản trị doanh nghiệp', 'KTTT'),
('IE203', 'Hệ thống quản trị qui trình nghiệp vụ', 'KTTT'),
('IE204', 'Tối ưu hóa công cụ tìm kiếm', 'KTTT'),
('IE205', 'Xử lý ảnh vệ tinh', 'KTTT'),
('IE206', 'Đồ án chuẩn bị tốt nghiệp', 'KTTT'),
('IE207', 'Đồ án', 'KTTT'),
('IE208', 'Kiến trúc và tích hợp hệ thống', 'KTTT'),
('IE209', 'Công nghệ Java', 'KTTT'),
('IE210', 'Hệ thống định vị toàn cầu (GPS)', 'KTTT'),
('IE211', 'Tin học môi trường', 'KTTT'),
('IE212', 'Công nghệ Dữ liệu lớn', 'KTTT'),
('IE213', 'Kỹ thuật phát triển hệ thống Web', 'KTTT'),
('IE216', 'Các chủ đề toán học cho KHDL', 'KTTT'),
('IE217', 'Máy học', 'KTTT'),
('IE218', 'Xử lý dữ liệu lớn', 'KTTT'),
('IE221', 'Kỹ thuật lập trình Python', 'KTTT'),
('IE222', 'Phân tích dữ liệu bằng Python', 'KTTT'),
('IE223', 'Phân tích dữ liệu bằng Python &R', 'KTTT'),
('IE224', 'Phân tích dữ liệu', 'KTTT'),
('IE225', 'Mạng kết nối', 'KTTT'),
('IE226', 'Đồ họa và trực quan hóa máy tính', 'KTTT'),
('IE227', 'Xử lý tín hiệu số cho mạng', 'KTTT'),
('IE228', 'Human-Computer Interaction', 'KTTT'),
('IE229', 'Artificial Intelligence', 'KTTT'),
('IE230', 'Viết báo cáo kỹ thuật bằng tiếng Nhật', 'KTTT'),
('IE231', 'Quản trị doanh nghiệp công nghệ thông tin', 'KTTT'),
('IE232', 'Nhập môn trí tuệ nhân tạo', 'KTTT'),
('IE233', 'Phân tích và mô hình mạng xã hội', 'KTTT'),
('IE301', 'Quản trị quan hệ khách hàng', 'KTTT'),
('IE302', 'Kiến trúc và tích hợp hệ thống', 'KTTT'),
('IE303', 'Công nghệ Java', 'KTTT'),
('IE304', 'Hệ thống định vị toàn cầu', 'KTTT'),
('IE305', 'Tin học môi trường', 'KTTT'),
('IE307', 'Công nghệ lập trình đa nền tảng cho ứng dụng di động', 'KTTT'),
('IE309', 'Thực tập doanh nghiệp', 'KTTT'),
('IE310', 'Tư duy thiết kế', 'KTTT'),
('IE313', 'Phân tích và trực quan dữ liệu', 'KTTT'),
('IE400', 'Chuyên đề tốt nghiệp', 'KTTT'),
('IE401', 'Tin-Sinh học', 'KTTT'),
('IE402', 'Hệ thống thông tin địa lý 3 chiều', 'KTTT'),
('IE403', 'Khai thác dữ liệu truyền thông xã hội', 'KTTT'),
('IE404', 'Khai phá truyền thông xã hội', 'KTTT'),
('IE405', 'Công nghệ phân tích dữ liệu lớn', 'KTTT'),
('IE406', 'Nhập môn ẩn thông tin và ứng dụng', 'KTTT'),
('IE501', 'Đồ án tốt nghiệp', 'KTTT'),
('IE502', 'Đồ án tốt nghiệp tại doanh nghiệp', 'KTTT'),
('IE505', 'Khóa luận tốt nghiệp', 'KTTT'),
('IEM4733', 'Tái cấu trúc quy trình doanh nghiệp', 'HTTT'),
('IEM5723', 'Mô hình hóa dữ liệu, quy trình và đối tượng', 'HTTT'),
('INI01', 'Thực tập quốc tế', 'P.DTDH'),
('INT001', 'Tiếng Anh tổng quát (tạm gọi)', 'HTTT'),
('INT002', 'Toeic 1', 'HTTT'),
('INT003', 'Tiếng Anh tổng quát 2 (tạm gọi)', 'HTTT'),
('INT004', 'Toeic 2', 'HTTT'),
('INT005', 'Tiếng Anh giao tiếp (tạm gọi)', 'HTTT'),
('INT006', 'Toeic 3', 'HTTT'),
('IS005', 'Giới thiệu ngành Hệ thống Thông tin', 'HTTT'),
('IS101', 'Thiết kế cơ sở dữ liệu', 'HTTT'),
('IS102', 'Các hệ cơ sở tri thức', 'HTTT'),
('IS103', 'Hệ quản trị cơ sở dữ liệu', 'HTTT'),
('IS104', 'Cơ sở dữ liệu phân tán', 'HTTT'),
('IS105', 'Hệ quản trị cơ sở dữ liệu Oracle', 'HTTT'),
('IS106', 'Khai thác dữ liệu', 'HTTT'),
('IS107', 'Hệ thống thông tin kế toán', 'HTTT'),
('IS201', 'Phân tích thiết kế hệ thống thông tin', 'HTTT'),
('IS202', 'Nhập môn công nghệ phần mềm', 'HTTT'),
('IS203', 'Lập trình cơ sở dữ liệu', 'HTTT'),
('IS204', 'Nhập môn hệ thống thông tin địa lý', 'HTTT'),
('IS205', 'PTTK hướng đối tượng với UML', 'HTTT'),
('IS206', 'Lập trình ứng dụng Web với Java', 'HTTT'),
('IS207', 'Phát triển ứng dụng web', 'HTTT'),
('IS208', 'Quản lý dự án công nghệ thông tin', 'HTTT'),
('IS210', 'Hệ quản trị cơ sở dữ liệu', 'HTTT'),
('IS211', 'Cơ sở dữ liệu phân tán', 'HTTT'),
('IS212', 'Thực tập tốt nghiệp', 'HTTT'),
('IS213', 'Đồ án xây dựng một hệ thống thông tin', 'HTTT'),
('IS214', 'Thiết kế cơ sở dữ liệu', 'HTTT'),
('IS215', 'Thiết kế hướng đối tượng với UML', 'HTTT'),
('IS216', 'Lập trình Java', 'HTTT'),
('IS217', 'Kho dữ liệu và OLAP', 'HTTT'),
('IS218', 'Kỹ năng tư vấn', 'HTTT'),
('IS219', 'Pháp luật trong Thương mại điện tử', 'HTTT'),
('IS220', 'Xây dựng HTTT trên các framework', 'HTTT'),
('IS225', 'Khai thác dữ liệu và ứng dụng', 'HTTT'),
('IS232', 'Hệ thống thông tin kế toán', 'HTTT'),
('IS251', 'Nhập môn Hệ thống thông tin địa lý', 'HTTT'),
('IS252', 'Khai thác dữ liệu', 'HTTT'),
('IS253', 'Lập trình ứng dụng trên thiết bị di động', 'HTTT'),
('IS254', 'Hệ hỗ trợ quyết định', 'HTTT'),
('IS301', 'Thương mại điện tử', 'HTTT'),
('IS302', 'Phân tích không gian', 'HTTT'),
('IS303', 'Hệ cơ sở dữ liệu không gian', 'HTTT'),
('IS3033', 'Quản lý dự án hệ thống thông tin', 'HTTT'),
('IS304', 'Kho dữ liệu và OLAP', 'HTTT'),
('IS305', 'An toàn và bảo mật HTTT', 'HTTT'),
('IS306', 'Hệ thống thông tin quản lý', 'HTTT'),
('IS311', 'Đồ án xây dựng hệ thống thông tin', 'HTTT'),
('IS3303', 'Phân tích thiết kế hệ thống', 'HTTT'),
('IS332', 'Hệ thống thông tin quản lý', 'HTTT'),
('IS334', 'Thương mại điện tử', 'HTTT'),
('IS335', 'An toàn và bảo mật hệ thống thông tin', 'HTTT'),
('IS336', 'Hoạch định nguồn lực doanh nghiệp', 'HTTT'),
('IS337', 'Cơ sở dữ liệu nâng cao', 'HTTT'),
('IS338', 'Dự báo kinh doanh', 'HTTT'),
('IS339', 'Sinh tin học', 'HTTT'),
('IS340', 'Thị trường chứng khoán', 'HTTT'),
('IS341', 'Khởi nghiệp', 'HTTT'),
('IS342', 'Chính phủ điện tử', 'HTTT'),
('IS343', 'Luật CNTT', 'HTTT'),
('IS344', 'Quản trị nguồn lực y tế', 'HTTT'),
('IS345', 'AI trong y tế', 'HTTT'),
('IS346', 'Quản lý dự án công nghệ thông tin y tế', 'HTTT'),
('IS347', 'Thống kê y học', 'HTTT'),
('IS348', 'Dịch tễ học', 'HTTT'),
('IS349', 'Hệ thống y tế', 'HTTT'),
('IS351', 'Phân tích không gian', 'HTTT'),
('IS352', 'Hệ cơ sở dữ liệu không gian', 'HTTT'),
('IS353', 'Mạng xã hội', 'HTTT'),
('IS354', 'Công nghệ tài chính căn bản Fintech', 'HTTT'),
('IS355', 'Công nghệ Blockchain', 'HTTT'),
('IS356', 'Agile IT với DevOps', 'HTTT'),
('IS357', 'Kiến trúc hướng dịch vụ', 'HTTT'),
('IS358', 'Kiểm soát nhiễm khuẩn bệnh viện', 'HTTT'),
('IS360', 'Quản lý chăm sóc và điều trị', 'HTTT'),
('IS361', 'Quản lý chuỗi cung ứng dược và thiết bị y tế', 'HTTT'),
('IS362', 'Quản trị tài chính và bảo hiểm y tế', 'HTTT'),
('IS363', 'Pháp luật trong lĩnh vực y tế', 'HTTT'),
('IS364', 'Mã tiêu chuẩn dùng chung trong y tế', 'HTTT'),
('IS401', 'Khóa luận tốt nghiệp', 'HTTT'),
('IS4013', 'Thiết kế, quản lý và quản trị hệ CSDL', 'HTTT'),
('IS402', 'Điện toán đám mây', 'HTTT'),
('IS403', 'Phân tích dữ liệu kinh doanh', 'HTTT'),
('IS404', 'Kho dữ liệu và OLAP', 'HTTT'),
('IS405', 'Dữ liệu lớn', 'HTTT'),
('IS406', 'Điện toán đám mây và xử lý dữ liệu lớn', 'HTTT'),
('IS407', 'Đồ án tốt nghiệp', 'HTTT'),
('IS4133', 'Công nghệ thông tin cho thương mại điện tử', 'HTTT'),
('IS4263', 'Các ứng dụng thông minh và hỗ trợ ra quyết định', 'HTTT'),
('IS4523', 'Hệ truyền thông dữ liệu', 'HTTT'),
('IS501', 'Thực tập cuối khóa', 'HTTT'),
('IS502', 'Thực tập doanh nghiệp', 'HTTT'),
('IS503', 'Đồ án tốt nghiệp tại doanh nghiệp', 'HTTT'),
('IS505', 'Khóa luận tốt nghiệp', 'HTTT'),
('IS5100', 'Thực tập cuối khóa', 'HTTT'),
('IS6301', 'Phân tích thiết kế
hệ thống thông tin nâng cao', 'HTTT'),
('IT001', 'Nhập môn lập trình', 'KHMT'),
('IT002', 'Lập trình hướng đối tượng', 'CNPM'),
('IT003', 'Cấu trúc dữ liệu và giải thuật', 'KHMT'),
('IT004', 'Cơ sở dữ liệu', 'HTTT'),
('IT005', 'Nhập môn mạng máy tính', 'MMT&TT'),
('IT006', 'Kiến trúc máy tính', 'KTMT'),
('IT007', 'Hệ điều hành', 'KTMT'),
('IT008', 'Lập trình trực quan', 'CNPM'),
('IT009', 'Giới thiệu ngành', 'P.DTDH'),
('IT010', 'Tổ chức và cấu trúc máy tính', 'KTMT'),
('IT011', 'Nhập môn lập trình thi đấu', 'KHMT'),
('IT012', 'Tổ chức và Cấu trúc Máy tính II', 'KTMT'),
('IT013', 'Cấu trúc dữ liệu cho lập trình thi đấu', 'KHMT'),
('ITEM1', 'Nhập môn Quản trị doanh nghiệp', 'P.DTDH'),
('ITEW1', 'Nhập môn công tác kỹ sư', 'TTNN'),
('ITNT005', 'Communication', 'HTTT'),
('JAN01', 'Tiếng Nhật 1', 'P.DTDH'),
('JAN02', 'Tiếng Nhật 2', 'P.DTDH'),
('JAN03', 'Tiếng Nhật 3', 'P.DTDH'),
('JAN04', 'Tiếng Nhật 4', 'P.DTDH'),
('JAN05', 'Tiếng Nhật 5', 'P.DTDH'),
('JAN06', 'Tiếng Nhật 6', 'P.DTDH'),
('JAN07', 'Tiếng Nhật 7', 'P.DTDH'),
('JAN08', 'Tiếng Nhật 8', 'P.DTDH'),
('JANHU', 'Tiếng Nhật miễn phí do Huredee tài trợ', 'P.DTDH'),
('LIA01', 'Đại số tuyến tính', 'BMTL'),
('LIA11', 'Đại số tuyến tính', 'BMTL'),
('MA001', 'Giải tích 1', 'BMTL'),
('MA002', 'Giải tích 2', 'BMTL'),
('MA003', 'Đại số tuyến tính', 'BMTL'),
('MA004', 'Cấu trúc rời rạc', 'BMTL'),
('MA005', 'Xác suất thống kê', 'BMTL'),
('MA006', 'Giải tích', 'BMTL'),
('MAT01', 'Toán cao cấp A1', 'BMTL'),
('MAT02', 'Toán cao cấp A2', 'BMTL'),
('MAT04', 'Cấu trúc rời rạc', 'BMTL'),
('MAT11', 'Giải tích 1', 'BMTL'),
('MAT12', 'Giải tích 2', 'BMTL'),
('MAT14', 'Toán rời rạc cho máy tính', 'BMTL'),
('MAT21', 'Toán cao cấp A1 (TE)', 'BMTL'),
('MAT22', 'Toán cao cấp A2 (TE)', 'BMTL'),
('MAT23', 'Đại số tuyến tính', 'BMTL'),
('MAT24', 'Cấu trúc rời rạc (TE)', 'BMTL'),
('MATH2144', 'Giải tích I', 'HTTT'),
('MATH2153', 'Giải tích II', 'HTTT'),
('MATH2154', 'Giải tích', 'HTTT'),
('MATH3013', 'Đại số tuyến tính', 'HTTT'),
('ME001', 'Giáo dục quốc phòng', 'P.DTDH'),
('MEDU1', 'Giáo dục quốc phòng', 'GDQP'),
('MKTG4223', 'Quản trị chuỗi cung ứng', 'HTTT'),
('MKTG5883', 'Khai phá dữ liệu và ứng dụng', 'HTTT'),
('MLPE1', 'Kinh tế chính trị Mác-Lênin (TE)', 'P.DTDH'),
('MLPE2', 'Kinh tế chính trị Mác-Lênin (TE1)', 'P.DTDH'),
('MM001', 'Kỹ năng truyền thông cho người làm CNTT', 'P.DTDH'),
('MM002', 'Truyền thông Kỹ thuật số', 'P.DTDH'),
('MM003', 'Quản trị sự kiện', 'CNPM'),
('MM004', 'Nguyên lý thiết kế đồ hoạ', 'CNPM'),
('MM005', 'Nhập môn marketing', 'CNPM'),
('MM006', 'Tâm lý học đại cương', 'CNPM'),
('MM007', 'Tư duy sáng tạo và xu hướng thiết kế truyền thông', 'CNPM'),
('MM008', 'Kỹ năng truyền thông ứng dụng', 'CNPM'),
('MM101', 'Giới thiệu ngành Truyền thông đa phương tiện', 'CNPM'),
('MM102', 'Lý luận truyền thông đại chúng', 'CNPM'),
('MM103', 'Cơ sở tạo hình và nguyên lý thị giác', 'CNPM'),
('MM104', 'Viết nội dung đa phương tiện', 'CNPM'),
('MM105', 'Nhập môn kỹ thuật sản xuất nội dung đa phương tiện', 'CNPM'),
('MM106', 'Thu thập và phân tích khám phá dữ liệu Truyền thông đa phương tiện', 'CNPM'),
('MM107', 'Học máy ứng dụng trong Truyền thông đa phương tiện', 'CNPM'),
('MM108', 'Tiếp thị số', 'CNPM'),
('MM109', 'Thiết kế đồ họa', 'CNPM'),
('MM110', 'Màu sắc và tâm lý thị giác trong thiết kế truyền thông', 'CNPM'),
('MM201', 'Truyền thông và dư luận xã hội', 'CNPM'),
('MM202', 'Học sâu ứng dụng trong truyền thông đa phương tiện', 'CNPM'),
('MM203', 'Xử lý ngôn ngữ tự nhiên cho truyền thông đa phương tiện', 'CNPM'),
('MM204', 'Xử lý ảnh số và video trong truyền thông đa phương tiện', 'CNPM'),
('MM205', 'Phân tích và hiểu nội dung đa phương thức', 'CNPM'),
('MM206', 'Dữ liệu lớn ứng dụng trong truyền thông đa phương tiện', 'CNPM'),
('MM207', 'Hệ thống khai phá dữ liệu mạng xã hội', 'CNPM'),
('MM208', 'Thiết kế và sản xuất ấn phẩm', 'CNPM'),
('MM209', 'Nghiệp vụ truyền thông và báo chí', 'CNPM'),
('MM210', 'Kỹ thuật quay phim biên kịch và hậu kỳ', 'CNPM'),
('MM211', 'Thực tế ảo và thực tế tăng cường', 'CNPM'),
('MM212', 'Hoạt hình', 'CNPM'),
('MM213', 'Quản lý dự án truyền thông đa phương tiện', 'CNPM'),
('MM214', 'Chiến lược phát triển thương hiệu', 'CNPM'),
('MM215', 'Quan hệ công chúng trong marketing', 'CNPM'),
('MM216', 'Tối ưu hóa và tiếp thị trên công cụ tìm kiếm', 'CNPM'),
('MM217', 'Tiếp thị cho sản phẩm dịch vụ', 'CNPM'),
('MM218', 'Xây dựng kênh tiếp thị trực tuyến', 'CNPM'),
('MM219', 'Quản trị mối quan hệ khách hàng định hướng dữ liệu', 'CNPM'),
('MM220', 'Phân tích dữ liệu truyền thông số', 'CNPM'),
('MM221', 'Chuyên đề các vấn đề hiện đại trong Truyền thông đa phương tiện', 'CNPM'),
('MM222', 'An ninh thông tin trong truyền thông đa phương tiện', 'CNPM'),
('MM223', 'Kể chuyện tương tác', 'CNPM'),
('MM224', 'Hình họa cơ bản', 'CNPM'),
('MM301', 'Đồ án Truyền thông đa phương tiện', 'CNPM'),
('MM302', 'Thực tập', 'CNPM'),
('MM304', 'Khởi nghiệp ngành Truyền thông đa phương tiện', 'CNPM'),
('MM504', 'Đồ án tốt nghiệp', 'CNPM'),
('MM505', 'Khóa luận tốt nghiệp', 'CNPM'),
('MM506', 'Đồ án tốt nghiệp tại doanh nghiệp', 'CNPM'),
('MSIS207', 'Phát triển ứng dụng web', 'HTTT'),
('MSIS2433', 'Lập trình hướng đối tượng', 'HTTT'),
('MSIS3033', 'Quản lý dự án hệ thống thông tin', 'HTTT'),
('MSIS3233', 'Khoa học quản lý', 'HTTT'),
('MSIS3242', 'Quản lý chất lượng phần mềm', 'HTTT'),
('MSIS3243', 'Lý thuyết quyết định quản lý', 'HTTT'),
('MSIS3303', 'Phân tích thiết kế hệ thống', 'HTTT'),
('MSIS4013', 'Thiết kế, quản lý và quản trị hệ CSDL', 'HTTT'),
('MSIS402', 'Điện toán đám mây', 'HTTT'),
('MSIS405', 'Dữ liệu lớn', 'HTTT'),
('MSIS406', 'Dữ liệu lớn trên nền điện toán đám mây', 'HTTT'),
('MSIS4133', 'Công nghệ thông tin trong thương mại điện tử', 'HTTT'),
('MSIS4243', 'Điều khiển và giám sát hệ thống thông tin', 'HTTT'),
('MSIS4263', 'Các ứng dụng thông minh và hỗ trợ ra quyết định', 'HTTT'),
('MSIS4363', 'Các chủ đề nâng cao trong phát triển hệ thống', 'HTTT'),
('MSIS4443', 'Các hệ thống mô phỏng trên máy tính', 'HTTT'),
('MSIS4523', 'Hệ truyền thông dữ liệu', 'HTTT'),
('MSIS4800', 'Hệ thống thông tin tính toán', 'HTTT'),
('MSIS4801', 'Quản lý thông tin địa lý', 'HTTT'),
('MSIS5723', 'Phân tích thiết kế hệ thống thông tin', 'HTTT'),
('NHJP1', 'Tiếng Nhật Sơ cấp 1', 'P.DTDH'),
('NHJP2', 'Tiếng Nhật Sơ cấp 2', 'P.DTDH'),
('NNH050', 'Ngôn ngữ quảng cáo', 'P.DTDH'),
('NT005', 'Giới thiệu ngành Mạng máy tính và Truyền thông dữ liệu', 'MMT&TT'),
('NT015', 'Giới thiệu ngành An toàn Thông tin', 'MMT&TT'),
('NT101', 'An toàn mạng máy tính', 'MMT&TT'),
('NT102', 'Điện tử cho công nghệ thông tin', 'MMT&TT'),
('NT103', 'Hệ điều hành Linux', 'MMT&TT'),
('NT104', 'Lý thuyết thông tin', 'MMT&TT'),
('NT105', 'Truyền dữ liệu', 'MMT&TT'),
('NT106', 'Lập trình mạng căn bản', 'MMT&TT'),
('NT107', 'Xử lý tín hiệu trong truyển thông', 'MMT&TT'),
('NT108', 'Mạng truyền thông và di động', 'MMT&TT'),
('NT109', 'Lập trình ứng dụng mạng', 'MMT&TT'),
('NT110', 'Tín hiệu và mạch', 'MMT&TT'),
('NT111', 'Thiết bị mạng và truyền thông ĐPT', 'MMT&TT'),
('NT112', 'Công nghệ mạng viễn thông', 'MMT&TT'),
('NT113', 'Thiết kế Mạng', 'MMT&TT'),
('NT114', 'Đồ án chuyên ngành', 'MMT&TT'),
('NT115', 'Thực tập doanh nghiệp', 'MMT&TT'),
('NT116', 'Kỹ năng mềm', 'MMT&TT'),
('NT117', 'Đồ án môn học Lập trình ứng dụng Mạng', 'MMT&TT'),
('NT118', 'Phát triển ứng dụng trên thiết bị di động', 'MMT&TT'),
('NT119', 'Mật mã học', 'MMT&TT'),
('NT121', 'Thiết bị mạng và truyền thông ĐPT', 'MMT&TT'),
('NT130', 'Cơ chế hoạt động của mã độc', 'MMT&TT'),
('NT131', 'Hệ thống nhúng Mạng không dây', 'MMT&TT'),
('NT132', 'Quản trị mạng và hệ thống', 'MMT&TT'),
('NT133', 'An toàn kiến trúc hệ thống', 'MMT&TT'),
('NT137', 'Kỹ thuật phân tích mã độc', 'MMT&TT'),
('NT140', 'An toàn mạng', 'MMT&TT'),
('NT201', 'Phân tích thiết kế hệ thống truyền thông và mạng', 'MMT&TT'),
('NT202', 'Đồ án môn Lập trình ứng dụng mạng', 'MMT&TT'),
('NT203', 'Đồ án chuyên ngành', 'MMT&TT'),
('NT204', 'Hệ thống tìm kiếm, phát hiện và ngăn ngừa xâm nhập', 'MMT&TT'),
('NT205', 'Tấn công mạng', 'MMT&TT'),
('NT206', 'Quản trị hệ thống mạng', 'MMT&TT'),
('NT207', 'Quản lý rủi ro và an toàn thông tin trong doanh nghiệp', 'MMT&TT'),
('NT208', 'Lập trình ứng dụng Web', 'MMT&TT'),
('NT209', 'Lập trình hệ thống', 'MMT&TT'),
('NT210', 'Thương mại Điện tử và Triển khai ứng dụng', 'MMT&TT'),
('NT211', 'An ninh nhân sự, định danh và chứng thực', 'MMT&TT'),
('NT212', 'An toàn dữ liệu, khôi phục thông tin sau sự cố', 'MMT&TT'),
('NT213', 'Bảo mật web và ứng dụng', 'MMT&TT'),
('NT215', 'Thực tập doanh nghiệp', 'MMT&TT'),
('NT216', 'Bảo mật hệ thống dữ liệu', 'MMT&TT'),
('NT219', 'Mật mã học', 'MMT&TT'),
('NT230', 'Cơ chế hoạt động của mã độc', 'MMT&TT'),
('NT301', 'Quản trị hệ thống mạng', 'MMT&TT'),
('NT302', 'Xây dựng chuẩn chính sách an toàn thông tin trong doanh nghiệp', 'MMT&TT'),
('NT303', 'Công nghệ thoại IP', 'MMT&TT'),
('NT304', 'Ứng dụng truyền thông và an ninh thông tin', 'MMT&TT'),
('NT305', 'Phát triển ứng dụng trên  thiết bị di động', 'MMT&TT'),
('NT306', 'Kỹ thuật lập trình mạng trên Linux', 'MMT&TT'),
('NT307', 'Xây dựng ứng dụng web', 'MMT&TT'),
('NT309', 'Lập trình trên Linux', 'MMT&TT'),
('NT310', 'Pháp chứng mạng di động', 'MMT&TT'),
('NT311', 'Công nghệ tường lửa và bảo vệ mạng ngoại vi', 'MMT&TT'),
('NT312', 'Bảo mật với smartcard và NFC', 'MMT&TT'),
('NT320', 'Công nghệ vệ tinh', 'MMT&TT'),
('NT321', 'Hệ thống tìm kiếm, phát hiện và ngăn ngừa xâm nhập', 'MMT&TT'),
('NT330', 'An toàn mạng không dây và di động', 'MMT&TT'),
('NT331', 'Xây dựng chuẩn chính sách an toàn thông tin trong doanh nghiệp', 'MMT&TT'),
('NT332', 'Xử lý tín hiệu trong truyền thông', 'MMT&TT'),
('NT333', 'Tính toán lưới', 'MMT&TT'),
('NT334', 'Pháp chứng kỹ thuật số', 'MMT&TT'),
('NT395', 'Phát triển ứng dụng trên thiết bị di động', 'MMT&TT'),
('NT401', 'An toàn mạng nâng cao', 'MMT&TT'),
('NT402', 'Công nghệ mạng viễn thông', 'MMT&TT'),
('NT403', 'Tính toán lưới', 'MMT&TT'),
('NT404', 'Khóa luận tốt nghiệp', 'MMT&TT'),
('NT405', 'Bảo mật Internet', 'MMT&TT'),
('NT406', 'Đồ án tốt nghiệp', 'MMT&TT'),
('NT407', 'Pháp chứng kỹ thuật số', 'MMT&TT'),
('NT408', 'Bảo mật trên Internet', 'MMT&TT'),
('NT501', 'Thực tập doanh nghiệp', 'MMT&TT'),
('NT502', 'Thương mại Điện tử và Triển khai ứng dụng', 'MMT&TT'),
('NT503', 'Bảo mật Internet', 'MMT&TT'),
('NT504', 'Tiểu luận tốt nghiệp', 'MMT&TT'),
('NT505', 'Khóa luận tốt nghiệp', 'MMT&TT'),
('NT506', 'Đồ án tốt nghiệp tại doanh nghiệp', 'MMT&TT'),
('NT507', 'Xây dựng ứng dụng web', 'MMT&TT'),
('NT508', 'Đồ án tốt nghiệp', 'MMT&TT'),
('NT509', 'Hệ thống đa tác tử di động thông minh', 'MMT&TT'),
('NT521', 'Lập trình an toàn và khai thác lỗ hổng phần mềm', 'MMT&TT'),
('NT522', 'Phương pháp học máy trong an toàn thông tin', 'MMT&TT'),
('NT523', 'An toàn thông tin trong kỷ nguyên máy tính lượng tử', 'MMT&TT'),
('NT524', 'Kiến trúc và Bảo mật Điện toán Đám mây', 'MMT&TT'),
('NT531', 'Đánh giá hiệu năng hệ thống mạng máy tính', 'MMT&TT'),
('NT532', 'Công nghệ Internet of things hiện đại', 'MMT&TT'),
('NT533', 'Hệ tính toán phân bố', 'MMT&TT'),
('NT534', 'An toàn mạng máy tính nâng cao', 'MMT&TT'),
('NT535', 'Bảo mật Internet of things', 'MMT&TT'),
('NT536', 'Công nghệ truyền thông đa phương tiện', 'MMT&TT'),
('NT537', 'Truyền thông xã hội và kinh doanh', 'MMT&TT'),
('NT538', 'Giải thuật xử lý song song và phân bố', 'MMT&TT'),
('NT539', 'AI ứng dụng trong mạng và truyền thông', 'MMT&TT'),
('NT540', 'Mạng không dây thế hệ mới', 'MMT&TT'),
('NT541', 'Công nghệ mạng khả lập trình', 'MMT&TT'),
('NT542', 'Lập trình kịch bản tự động hóa cho quản trị và bảo mật mạng', 'MMT&TT'),
('NT543', 'Tín hiệu và hệ thống thông tin', 'MMT&TT'),
('NT544', 'Ăng ten và truyền thông vô tuyến', 'MMT&TT'),
('NT545', 'Thiết kế hệ thống viễn thông', 'MMT&TT'),
('NT546', 'Thiết kế và triển khai mạng tốc độ cao', 'MMT&TT'),
('NT547', 'Blockchain: Nền tảng, ứng dụng và bảo mật', 'MMT&TT'),
('NT548', 'Công nghệ DevOps và ứng dụng', 'MMT&TT'),
('NT549', 'Học máy tăng cường cho các hệ thống mạng', 'MMT&TT'),
('OOPT1', 'Lập trình hướng đối tượng', 'CNPM'),
('OOPT2', 'Lập trình hướng đối tượng', 'CNPM'),
('OSYS1', 'Hệ điều hành', 'MMT&TT'),
('OSYS2', 'Hệ điều hành', 'MMT&TT'),
('PE001', 'Giáo dục thể chất 1', 'P.DTDH'),
('PE002', 'Giáo dục thể chất 2', 'P.DTDH'),
('PE003', 'Giáo dục thể chất 3', 'TTNN'),
('PE012', 'Giáo dục thể chất', 'P.DTDH'),
('PE231', 'Giáo dục thể chất 1', 'P.DTDH'),
('PE232', 'Giáo dục thể chất 2', 'P.DTDH'),
('PEDU1', 'Giáo dục thể chất 1', 'GDTC'),
('PEDU2', 'Giáo dục thể chất 2', 'P.DTDH'),
('PH001', 'Nhập môn điện tử', 'BMTL'),
('PH002', 'Nhập môn mạch số', 'KTMT'),
('PH003', 'Vật lý kỹ thuật', 'BMTL'),
('PHIL1', 'Những NLCB của chủ nghĩa Mác-Lênin', 'BMAV'),
('PHIL2', 'Triết học Mác-Lênin', 'P.DTDH'),
('PHY01', 'Vật lý đại cương A1', 'BMTL'),
('PHY02', 'Vật lý đại cương A2', 'BMTL'),
('PHY03', 'Vật lý đại cương A3', 'BMTL'),
('PHY11', 'General Physics 1', 'BMTL'),
('PHY12', 'General Physics 2', 'BMTL'),
('PHY22', 'Vật lý đại cương A2 (TE1)', 'BMTL'),
('PHYS1114', 'Vật lý đại cương I', 'HTTT'),
('PHYS1214', 'Vật lý đại cương II', 'HTTT'),
('PHYS1215', 'Vật lý đại cương', 'HTTT'),
('QTE111', 'Văn hóa giao tiếp', 'P.DTDH'),
('SC203', 'Phương pháp khoa học', 'HTTT'),
('SE005', 'Giới thiệu ngành Kỹ thuật Phần mềm', 'CNPM'),
('SE100', 'Phương pháp Phát triển phần mềm hướng đối tượng', 'CNPM'),
('SE101', 'Phương pháp mô hình hóa', 'CNPM'),
('SE102', 'Nhập môn phát triển game', 'CNPM'),
('SE103', 'Các phương pháp lập trình', 'CNPM'),
('SE104', 'Nhập môn Công nghệ phần mềm', 'CNPM'),
('SE105', 'Lập trình nhúng căn bản', 'CNPM'),
('SE106', 'Đặc tả hình thức', 'CNPM'),
('SE107', 'Phân tích thiết kế hệ thống', 'CNPM'),
('SE108', 'Kiểm chứng phần mềm', 'CNPM'),
('SE109', 'Phát triển, vận hành, bảo trì phần mềm', 'CNPM'),
('SE110', 'Phương pháp Phát triển phần mềm hướng đối tượng', 'CNPM'),
('SE111', 'Đồ án mã nguồn mở', 'CNPM'),
('SE112', 'Đồ án chuyên ngành', 'CNPM'),
('SE113', 'Kiểm chứng phần mềm', 'CNPM'),
('SE114', 'Nhập môn ứng dụng di động', 'CNPM'),
('SE115', 'Phát triển game với Unity', 'CNPM'),
('SE116', 'Phát triển kỹ năng lập trình Game ứng dụng trong thực tế', 'CNPM'),
('SE117', 'Kỹ thuật lập trình', 'CNPM'),
('SE121', 'Đồ án 1', 'CNPM'),
('SE122', 'Đồ án 2', 'CNPM'),
('SE207', 'Phân tích thiết kế hệ thống', 'CNPM'),
('SE208', 'Kiểm chứng phần mềm', 'CNPM'),
('SE209', 'Phát triển, vận hành, bảo trì phần mềm', 'CNPM'),
('SE210', 'Quản lý dự án công nghệ thông tin', 'CNPM'),
('SE211', 'Phát triển phần mềm hướng đối tượng', 'CNPM'),
('SE212', 'Phát triển phần mềm mã nguồn mở', 'CNPM'),
('SE213', 'Xử lý phân bố', 'CNPM'),
('SE214', 'Công nghệ phần mềm chuyên sâu', 'CNPM'),
('SE215', 'Giao tiếp người máy', 'CNPM'),
('SE220', 'Thiết kế Game', 'CNPM'),
('SE221', 'Lập trình game nâng cao', 'CNPM'),
('SE301', 'Phát triển phần mềm mã nguồn mở', 'CNPM'),
('SE310', 'Công nghệ .NET', 'CNPM'),
('SE311', 'Ngôn ngữ lập trình Java', 'CNPM'),
('SE312', 'Công nghệ .NET', 'CNPM'),
('SE313', 'Một số thuật toán thông minh', 'CNPM'),
('SE314', 'Công nghệ game 3D', 'CNPM'),
('SE315', 'Công nghệ game online', 'CNPM'),
('SE316', 'Phát triển Game đa nền tảng', 'CNPM'),
('SE317', 'Công nghệ tiên tiến trong phát triển game', 'CNPM'),
('SE320', 'Lập trình đồ họa 3 chiều với Direct3D', 'CNPM'),
('SE321', 'Lập trình trên thiết bị di động', 'CNPM'),
('SE322', 'Công nghệ Web và ứng dụng', 'CNPM'),
('SE323', 'Thiết kế Game', 'CNPM'),
('SE324', 'Nhập môn lập trình 3D game', 'CNPM'),
('SE325', 'Chuyên đề J2EE', 'CNPM'),
('SE326', 'Cơ sở dữ liệu nâng cao', 'CNPM'),
('SE327', 'Phát triển và vận hành game', 'CNPM'),
('SE328', 'Lập trình TTNT trong Game', 'CNPM'),
('SE329', 'Thiết kế 3D Game Engine', 'CNPM'),
('SE330', 'Ngôn ngữ lập trình Java', 'CNPM'),
('SE331', 'Chuyên đề E-commerce', 'CNPM'),
('SE332', 'Chuyên đề CSDL nâng cao', 'CNPM'),
('SE333', 'Chuyên đề E-Government', 'CNPM'),
('SE334', 'Các phương pháp lập trình', 'CNPM'),
('SE335', 'Công nghệ XML và ứng dụng', 'CNPM'),
('SE336', 'Phương pháp luận sáng tạo KH-CN', 'CNPM'),
('SE337', 'Các thuật toán thông minh', 'CNPM'),
('SE338', 'Logic mờ', 'CNPM'),
('SE339', 'Xử lý phân bổ', 'CNPM'),
('SE340', 'Quản lý dự án công nghệ thông tin', 'CNPM'),
('SE341', 'Công nghệ Web và ứng dụng', 'CNPM'),
('SE342', 'Logic mờ', 'CNPM'),
('SE343', 'Công nghệ Portal', 'CNPM'),
('SE344', 'Lập trình game trong các thiết bị di động', 'CNPM'),
('SE345', 'Kỹ thuật lập trình nhúng', 'CNPM'),
('SE346', 'Lập trình trên thiết bị di động', 'CNPM'),
('SE347', 'Công nghệ Web và ứng dụng', 'CNPM'),
('SE348', 'Chuyên đề M-commerce', 'CNPM'),
('SE349', 'Nhập môn Quản trị doanh nghiệp', 'CNPM'),
('SE350', 'Chuyên đề E-learning', 'CNPM'),
('SE351', 'Xử lý song song', 'CNPM'),
('SE352', 'Phát triển ứng dụng VR', 'CNPM'),
('SE354', 'Chuyên đề các quy trình phát triển phần mềm hiện đại', 'CNPM'),
('SE355', 'Máy học và các công cụ', 'CNPM'),
('SE356', 'Kiến trúc Phần mềm', 'CNPM'),
('SE357', 'Kỹ thuật phân tích yêu cầu', 'CNPM'),
('SE358', 'Quản lý dự án Phát triển Phần mềm', 'CNPM'),
('SE359', 'DevOps trong phát triển phần mềm', 'CNPM'),
('SE360', 'Điện toán đám mây và phát triển ứng dụng hướng dịch vụ', 'CNPM'),
('SE361', 'Phát triển Phần mềm theo Kiến trúc Microservices', 'CNPM'),
('SE362', 'An toàn phần mềm và hệ thống', 'CNPM'),
('SE363', 'Phát triển ứng dụng trên nền tảng dữ liệu lớn', 'CNPM'),
('SE364', 'Thiết kế giao diện và trải nghiệm người dùng', 'CNPM'),
('SE365', 'Học sâu ứng dụng trong phát triển phần mềm', 'CNPM'),
('SE400', 'Seminar các vấn đề hiện đại của CNPM', 'CNPM'),
('SE401', 'Mẫu thiết kế', 'CNPM'),
('SE402', 'Điện toán đám mây', 'CNPM'),
('SE403', 'Nguyên lý thiết kế thế giới ảo', 'CNPM'),
('SE404', 'Chuyên đề E-Government', 'CNPM'),
('SE405', 'Chuyên đề Mobile and Pervasive Computing', 'CNPM'),
('SE406', 'Mẫu thiết kế hướng đối tượng', 'CNPM'),
('SE407', 'Chuyên đề Pervasive and Mobile Computing', 'CNPM'),
('SE408', 'Phát triển game với Blockchain', 'CNPM'),
('SE409', 'Phát triển dự án Game', 'CNPM'),
('SE417', 'Đồ án môn học mã nguồn mở', 'CNPM'),
('SE418', 'Đồ án môn học chuyên ngành', 'CNPM'),
('SE501', 'Thực tập tốt nghiệp', 'CNPM'),
('SE502', 'Thực tập', 'CNPM'),
('SE503', 'Đồ án', 'CNPM'),
('SE505', 'Khóa luận tốt nghiệp', 'CNPM'),
('SE506', 'Đồ án tốt nghiệp tại doanh nghiệp', 'CNPM'),
('SE507', 'Đồ án tốt nghiệp', 'CNPM'),
('SMET1', 'Phương pháp NCKH trong tin học', 'P.DTDH'),
('SMET2', 'Phương pháp luận sáng tạo KH-CN', 'P.DTDH'),
('SOCI1', 'Chủ nghĩa xã hội khoa học', 'P.DTDH'),
('SP3724', 'Kỹ năng giao tiếp', 'HTTT'),
('SPCH2713', 'Kỹ năng giao tiếp', 'HTTT'),
('SPCH3723', 'Tiếng Anh chuyên ngành CNTT', 'HTTT'),
('SPCH3724', 'Kỹ năng giao tiếp', 'HTTT'),
('SS001', 'Những nguyên lý cơ bản của chủ nghĩa Mác Lênin', 'P.DTDH'),
('SS002', 'Đường lối cách mạng của Đảng CS Việt Nam', 'P.DTDH'),
('SS003', 'Tư tưởng Hồ Chí Minh', 'P.DTDH'),
('SS004', 'Kỹ năng nghề nghiệp', 'P.DTDH'),
('SS005', 'Phương pháp luận sáng tạo KH-CN', 'P.DTDH'),
('SS006', 'Pháp luật đại cương', 'P.DTDH'),
('SS007', 'Triết học Mác – Lênin', 'P.DTDH'),
('SS008', 'Kinh tế chính trị Mác – Lênin', 'P.DTDH'),
('SS009', 'Chủ nghĩa xã hội khoa học', 'P.DTDH'),
('SS010', 'Lịch sử Đảng Cộng sản Việt Nam', 'P.DTDH'),
('SSKL1', 'Kỹ năng mềm', 'P.DTDH'),
('STA01', 'Xác suất thống kê', 'BMAV'),
('STAT11', 'Xác xuất thống kê', 'HTTT'),
('STAT3013', 'Phân tích thống kê', 'HTTT'),
('STAT4033', 'Thống kê', 'HTTT'),
('THU086', 'Đào tạo năng lực thông tin', 'P.DTDH'),
('THU107', 'Truyền thông xã hội trong các tổ chức', 'P.DTDH'),
('TLH025', 'Tâm lý học nhân cách', 'P.DTDH'),
('TOEIC 450', 'TOEIC 450', 'TTNN'),
('TOEIC450', 'TOEIC 450', 'TTNN'),
('VCPH1', 'Lịch sử Đảng CSVN', 'P.DTDH'),
('VCPL1', 'Đường lối cách mạng của Đảng CSVN', 'TTNN'),
('WINP1', 'Lập trình trên Windows', 'CNPM');

